CREATE DATABASE RNSITDB;
use RNSITDB;


CREATE TABLE STUDENT(
USN varchar(10) NOT NULL,
STUDENT_FNAME varchar(100) DEFAULT NULL,
STUDENT_LNAME varchar(100) DEFAULT NULL,
GENDER varchar(7) DEFAULT NULL,
EMAIL_ID varchar(64) DEFAULT NULL,
BLOOD_GROUP varchar(4),
DEPT_NAME varchar(10),
CUR_SEM int DEFAULT NULL,
CURRENT_ADDRESS varchar(300) DEFAULT NULL,
PERMANENT_ADDRESS varchar(300) DEFAULT NULL,
DOB date DEFAULT NULL,
HOSTEL_OR_DAYSCHOLAR varchar(20) DEFAULT NULL,
DOC_RETURN_STATUS BOOLEAN DEFAULT 0,
PRIMARY KEY (USN)
);

CREATE TABLE DEPARTMENTLIST(
    DEPT_NAME VARCHAR(20),
    DEPT_ID VARCHAR(20),
    PRIMARY KEY (DEPT_ID)
);


CREATE TABLE DEPARTMENTCOURSEINFO(
    DEPT_ID VARCHAR(20),
    SUBCODE VARCHAR(10) NOT NULL,
    SUBJECTNAME VARCHAR(50),
    NO_OF_CREDITS INT,
    NO_OF_HOURS_PER_WEEK INT,
    TOTAL_NO_OF_CONTACT_HOURS INT,
    PRIMARY KEY (SUBCODE),
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTLIST(DEPT_ID)
);

CREATE TABLE ATTENDANCE(
SLNO integer,
USN varchar(10) NOT NULL,
SUB_CODE varchar(7) NOT NULL,
CLASSES_ATTENDED int DEFAULT NULL,
TOTAL_CLASSES int DEFAULT NULL,
PERCENTAGE decimal(10,2) DEFAULT NULL,
PRIMARY KEY(SLNO,USN,SUB_CODE),
FOREIGN KEY(USN) REFERENCES Student(USN),
FOREIGN KEY(SUB_CODE) REFERENCES DEPARTMENTCOURSEINFO(SUBCODE)
);


CREATE TABLE FEES(
USN varchar(10) NOT NULL,
COLLEGE_FEE int,
HOSTEL_FEE int  DEFAULT NULL,
LIBRARY_FINES int DEFAULT NULL,
OTHER_FINES int DEFAULT NULL,
PRIMARY KEY(USN),
FOREIGN KEY(USN) REFERENCES Student(USN)
);

CREATE TABLE HOSTEL(
USN varchar(10) NOT NULL,
GIRLS_OR_BOYS_HOSTEL varchar(5) DEFAULT NULL,
ROOM_NO varchar(5) NOT NULL,
BLOCK_NAME varchar(10) DEFAULT NULL,
PRIMARY KEY(USN),
FOREIGN KEY(USN) REFERENCES Student(USN)
);

CREATE TABLE AADHAR(
    AADHAR_NO BIGINT NOT NULL,
    USN VARCHAR(10) NOT NULL,
    PRIMARY KEY(AADHAR_NO),
    FOREIGN KEY(USN) REFERENCES Student(USN)
);

 CREATE TABLE PARENT(
    USN varchar(10) NOT NULL,
    PARENT_OR_GAURDIAN VARCHAR(15),
	FNAME VARCHAR(50),
    FATHER_OCCUPATION VARCHAR(50),
    FPHONE_NO INT,
    FEMAIL_ID VARCHAR(100),
    MNAME VARCHAR(50),
    MOTHER_OCCUPATION VARCHAR(50),
    MPHONE_NO INT,
    MEMAIL_ID VARCHAR(100),
    PRIMARY KEY(USN),
    FOREIGN KEY(USN) REFERENCES Student(USN)
 );

CREATE TABLE MARKS(
	SLNO integer, 
    USN varchar(10) NOT NULL,
    SEMESTER INT,
    SUBCODE VARCHAR(10) NOT NULL,
    IA1_SCORES INT,
    IA2_SCORES INT,
    IA3_SCORES INT,
    PRIMARY KEY(SLNO,USN,SUBCODE),
    FOREIGN KEY(USN) REFERENCES Student(USN),
    FOREIGN KEY(SUBCODE) REFERENCES DEPARTMENTCOURSEINFO(SUBCODE)
);

CREATE TABLE BACKLOGS(
    SLNO integer,
    USN varchar(10) NOT NULL,
    BACKLOGS_SUB_CODE VARCHAR(100),
    PRIMARY KEY(SLNO,USN,BACKLOGS_SUB_CODE),
    FOREIGN KEY(USN) REFERENCES STUDENT(USN)
);


CREATE TABLE TEACHERSLIST(
	SLNO INTEGER,
    TID VARCHAR(10) NOT NULL,
    TNAME VARCHAR(50),
    SUBCODE VARCHAR(10) NOT NULL,
    PRIMARY KEY(SLNO,TID,TNAME),
    FOREIGN KEY(SUBCODE) REFERENCES DEPARTMENTCOURSEINFO(SUBCODE)
);

CREATE TABLE IMP_INFO(
    USN varchar(10) NOT NULL,
    10TH_PERCENTAGE BIGINT,
    12TH_PERCENTAGE BIGINT,
    NAME_OF_SCHOOL_10TH VARCHAR(50),
    NAME_OF_COLLEGE_12TH VARCHAR(50),
    BOARD_OF_EDUCATION_10TH VARCHAR(10),
    BOARD_OF_EDUCATION_12TH VARCHAR(10),
    YEAR_OF_PASSING_10TH INT,
    YEAR_OF_PASSING_12TH INT,
    EDUCATION_GAP INT,
    ADMISSION_QUOTA_NAME VARCHAR(10),
    RANK_FROM_ENTRANCE BIGINT,
    BANK_NAME VARCHAR(20),
    BANK_ACCOUNT_NO BIGINT,
    PAN_NO BIGINT,
    VOTER_ID_NO BIGINT,
    PASSPORT_NO BIGINT,
    LINKEDIN_ID VARCHAR(20) NOT NULL,
    GITHUB_ID VARCHAR(20),
    AWARDS  VARCHAR(20),
    CERTIFICATES VARCHAR(20),
    PRIMARY KEY(LINKEDIN_ID),
    FOREIGN KEY(USN) REFERENCES Student(USN)
);
                 


