create database if not exists CDB;

use CDB;

CREATE TABLE STUDENT(
SID varchar(10) NOT NULL,
STUDENT_FNAME varchar(100) DEFAULT NULL,
STUDENT_LNAME varchar(100) DEFAULT NULL,
GENDER varchar(7) DEFAULT NULL,
EMAIL_ID varchar(64) DEFAULT NULL,
DEPT_NAME varchar(10),
CUR_SEM int DEFAULT NULL,
CURRENT_ADDRESS varchar(300) DEFAULT NULL,
PERMANENT_ADDRESS varchar(300) DEFAULT NULL,
DOB date DEFAULT NULL,
HOSTEL_OR_DAYSCHOLAR varchar(20) DEFAULT NULL,
DOC_RETURN_STATUS BOOLEAN DEFAULT 0,
PRIMARY KEY (SID)
);

CREATE TABLE DEPARTMENT(
    DEPT_NAME VARCHAR(20),
    SUBCODE VARCHAR(10) NOT NULL,
    SUBJECTNAME TEXT(30),
    NO_OF_CREDITS INT,
    NO_OF_HOURS_PER_WEEK INT,
    TOTAL_NO_OF_CONTACT_HOURS INT,
    PRIMARY KEY (SUBCODE)
);

CREATE TABLE ATTENDANCE(
STDID varchar(10) NOT NULL,
SUBCODE1 varchar(7) NOT NULL,
CLASSES_ATTENDED1 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES1 int DEFAULT NULL,
SUBCODE2 varchar(7) NOT NULL,
CLASSES_ATTENDED2 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES2 int DEFAULT NULL,
SUBCODE3 varchar(7) NOT NULL,
CLASSES_ATTENDED3 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES3 int DEFAULT NULL,
SUBCODE4 varchar(7) NOT NULL,
CLASSES_ATTENDED4 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES4 int DEFAULT NULL,
SUBCODE5 varchar(7) NOT NULL,
CLASSES_ATTENDED5 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES5 int DEFAULT NULL,
SUBCODE6 varchar(7) NOT NULL,
CLASSES_ATTENDED6 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES6 int DEFAULT NULL,
SUBCODE7 varchar(7) NOT NULL,
CLASSES_ATTENDED7 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES7 int DEFAULT NULL,
SUBCODE8 varchar(7) NOT NULL,
CLASSES_ATTENDED8 int DEFAULT NULL,
TOTAL_NO_OF_CLASSES8 int DEFAULT NULL,
FOREIGN KEY(STDID) REFERENCES Student(SID),
PRIMARY KEY(STDID)
);

CREATE TABLE FEES(
STDID varchar(10) NOT NULL,
COLLEGE_FEE int,
HOSTEL_FEE int  DEFAULT NULL,
LIBRARY_FINES int DEFAULT NULL,
OTHER_FINES int DEFAULT NULL,
PRIMARY KEY(STDID , COLLEGE_FEE),
FOREIGN KEY(STDID) REFERENCES Student(SID)
);

CREATE TABLE HOSTEL(
STDID varchar(10) NOT NULL,
GIRLS_OR_BOYS_HOSTEL varchar(5) DEFAULT NULL,
ROOM_NO varchar(5) NOT NULL,
BLOCK_NAME varchar(10) DEFAULT NULL,
PRIMARY KEY(STDID , ROOM_NO),
FOREIGN KEY(STDID) REFERENCES Student(SID)
);

CREATE TABLE AADHAR(
    AADHAR_NO BIGINT NOT NULL,
    STID VARCHAR(10) NOT NULL,
    PRIMARY KEY(AADHAR_NO),
    FOREIGN KEY(STID) REFERENCES Student(SID)
);

 CREATE TABLE PARENT(
    STDID varchar(10) NOT NULL,
    PNAME VARCHAR(100) NOT NULL,
    PARENT_OR_GAURDIAN VARCHAR(15),
	PHONE_NO INT,
    ALT_PH_NO INT,
    FATHER_OCCUPATION VARCHAR(50),
    MOTHER_OCCUPATION VARCHAR(50),
    EMAIL_ID VARCHAR(100),
    PRIMARY KEY(STDID,PNAME),
    FOREIGN KEY(STDID) REFERENCES Student(SID)
 );

CREATE TABLE MARKS(
    STDID varchar(10) NOT NULL,
    SEMESTER INT,
    SUBCODE VARCHAR(10) NOT NULL,
    IA1_SCORES INT,
    IA2_SCORES INT,
    IA3_SCORES INT,
    PRIMARY KEY(STDID , SUBCODE),
    FOREIGN KEY(STDID) REFERENCES Student(SID),
    FOREIGN KEY(SUBCODE) REFERENCES DEPARTMENT(SUBCODE)
);

CREATE TABLE BACKLOGS(
    STDID varchar(10) NOT NULL,
    BACKLOGS_SUB_CODE VARCHAR(100),
    PRIMARY KEY(STDID,BACKLOGS_SUB_CODE),
    FOREIGN KEY(STDID) REFERENCES STUDENT(SID)
);

CREATE TABLE TEACHER(
    TID VARCHAR(10) NOT NULL,
    TNAME VARCHAR(50),
    SUBCODE VARCHAR(10) NOT NULL,
    SUBNAME VARCHAR(50),
    FOREIGN KEY(SUBCODE) REFERENCES DEPARTMENT(SUBCODE),
    PRIMARY KEY(TID,SUBCODE)
);

CREATE TABLE IMP_INFO(
    STDID varchar(10) NOT NULL,
    10TH_PERCENTAGE BIGINT,
    12TH_PERCENTAGE BIGINT,
    NAME_OF_SCHOOL_10TH VARCHAR(50),
    NAME_OF_COLLEGE_12TH VARCHAR(50),
    BOARD_OF_EDUCATION_10TH VARCHAR(10),
    BOARD_OF_EDUCATION_12TH VARCHAR(10),
    YEAR_OF_PASSING_10TH INT,
    YEAR_OF_PASSING_12TH INT,
    EDUCATION_GAP INT,
    ADMISSION_QUOTA_NAME VARCHAR(10),
    RANK_FROM_ENTRANCE BIGINT,
    BANK_NAME VARCHAR(20),
    BANK_ACCOUNT_NO BIGINT,
    PAN_NO BIGINT,
    VOTER_ID_NO BIGINT,
    PASSPORT_NO BIGINT,
    LINKEDIN_ID VARCHAR(20) NOT NULL,
    GITHUB_ID VARCHAR(20),
    AWARDS  VARCHAR(20),
    CERTIFICATES VARCHAR(20),
    PRIMARY KEY(LINKEDIN_ID),
    FOREIGN KEY(STDID) REFERENCES Student(SID)
);
                 
SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;
SELECT * FROM HOSTEL;
SELECT * FROM BACKLOGS;
SELECT * FROM MARKS;
SELECT * FROM IMP_INFO;
SELECT * FROM TEACHER;
SELECT * FROM ATTENDANCE;
SELECT * FROM FEES;
SELECT * FROM PARENT;


