# Generated by Django 4.1.2 on 2023-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_subjects_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
