# Generated by Django 4.1.7 on 2023-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
