# Generated by Django 4.2 on 2023-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0006_alter_attendance_attendance_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test1", models.FloatField()),
                ("test2", models.FloatField()),
                ("test3", models.FloatField()),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
