# Generated by Django 4.1.2 on 2023-04-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_leavereportstudent_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='section',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
