# Generated by Django 4.1.7 on 2023-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_students_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
