# Generated by Django 4.1.2 on 2023-04-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_students_section_alter_students_course_id'),
        ('student_management_app', '0009_leavereportstaff_leave_status'),
    ]

    operations = [
    ]
