# Generated by Django 4.1.2 on 2023-05-07 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_alter_students_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='StudentTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('test1', models.FloatField()),
                ('test2', models.FloatField()),
                ('test3', models.FloatField()),
                ('attendance', models.IntegerField()),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects', to_field='subject_code')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
