# Generated by Django 4.1.2 on 2023-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_alter_subjects_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
