# Generated by Django 4.1.2 on 2023-05-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_alter_subjects_subject_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveReportStaff',
            new_name='StaffLeave',
        ),
    ]
