# Generated by Django 4.1.2 on 2023-05-08 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_rename_leavereportstaff_staffleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
