# Generated by Django 4.1.2 on 2023-05-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_alter_staffleave_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staff'),
        ),
    ]
