# Generated by Django 4.1.2 on 2023-05-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_alter_feedbackstaff_staff_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveReportStudent',
            new_name='StudentLeave',
        ),
    ]
