# Generated by Django 4.1.2 on 2023-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0025_rename_leavereportstudent_studentleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='leave_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='leave_status',
            field=models.BooleanField(default=0),
        ),
    ]
