# Generated by Django 4.1.7 on 2023-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0027_alter_staffleave_leave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='father_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='father_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='gaurdian_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='gaurdian_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='mother_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='mother_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_or_gaurdian_email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
