# Generated by Django 4.1.7 on 2023-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0029_adminhod_gender_staff_department_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gaurdian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_or_gaurdian_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
