# Generated by Django 4.1.7 on 2023-05-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0030_alter_students_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='father_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='gaurdian_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
