# Generated by Django 4.1.2 on 2023-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0031_alter_students_father_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gaurdian_num',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
