# Generated by Django 4.1.2 on 2023-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0032_alter_students_gaurdian_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gaurdian_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
