# Generated by Django 4.1.2 on 2023-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0034_alter_students_gaurdian_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
