# Generated by Django 4.1.2 on 2023-05-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0035_adminhod_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
