# Generated by Django 4.1.2 on 2023-05-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0037_subjects_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('test1_date', models.DateField()),
                ('test2_date', models.DateField()),
                ('test3_date', models.DateField()),
                ('subject_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
            ],
        ),
    ]
