# Generated by Django 4.1.2 on 2023-05-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0039_testscores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testdetails',
            unique_together={('subject_code', 'semester')},
        ),
    ]
