# Generated by Django 4.1.2 on 2023-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0040_alter_testdetails_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='department',
        ),
    ]
