# Generated by Django 4.1.2 on 2023-01-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhar_no', models.BigIntegerField(db_column='AADHAR_NO', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aadhar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departmentcourseinfo',
            fields=[
                ('subcode', models.CharField(db_column='SUBCODE', max_length=10, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(blank=True, db_column='SUBJECTNAME', max_length=50, null=True)),
                ('no_of_credits', models.IntegerField(blank=True, db_column='NO_OF_CREDITS', null=True)),
                ('no_of_hours_per_week', models.IntegerField(blank=True, db_column='NO_OF_HOURS_PER_WEEK', null=True)),
                ('total_no_of_contact_hours', models.IntegerField(blank=True, db_column='TOTAL_NO_OF_CONTACT_HOURS', null=True)),
            ],
            options={
                'db_table': 'departmentcourseinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departmentlist',
            fields=[
                ('dept_name', models.CharField(blank=True, db_column='DEPT_NAME', max_length=20, null=True)),
                ('dept_id', models.CharField(db_column='DEPT_ID', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'departmentlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImpInfo',
            fields=[
                ('number_10th_percentage', models.BigIntegerField(blank=True, db_column='10TH_PERCENTAGE', null=True)),
                ('number_12th_percentage', models.BigIntegerField(blank=True, db_column='12TH_PERCENTAGE', null=True)),
                ('name_of_school_10th', models.CharField(blank=True, db_column='NAME_OF_SCHOOL_10TH', max_length=50, null=True)),
                ('name_of_college_12th', models.CharField(blank=True, db_column='NAME_OF_COLLEGE_12TH', max_length=50, null=True)),
                ('board_of_education_10th', models.CharField(blank=True, db_column='BOARD_OF_EDUCATION_10TH', max_length=10, null=True)),
                ('board_of_education_12th', models.CharField(blank=True, db_column='BOARD_OF_EDUCATION_12TH', max_length=10, null=True)),
                ('year_of_passing_10th', models.IntegerField(blank=True, db_column='YEAR_OF_PASSING_10TH', null=True)),
                ('year_of_passing_12th', models.IntegerField(blank=True, db_column='YEAR_OF_PASSING_12TH', null=True)),
                ('education_gap', models.IntegerField(blank=True, db_column='EDUCATION_GAP', null=True)),
                ('admission_quota_name', models.CharField(blank=True, db_column='ADMISSION_QUOTA_NAME', max_length=10, null=True)),
                ('rank_from_entrance', models.BigIntegerField(blank=True, db_column='RANK_FROM_ENTRANCE', null=True)),
                ('bank_name', models.CharField(blank=True, db_column='BANK_NAME', max_length=20, null=True)),
                ('bank_account_no', models.BigIntegerField(blank=True, db_column='BANK_ACCOUNT_NO', null=True)),
                ('pan_no', models.BigIntegerField(blank=True, db_column='PAN_NO', null=True)),
                ('voter_id_no', models.BigIntegerField(blank=True, db_column='VOTER_ID_NO', null=True)),
                ('passport_no', models.BigIntegerField(blank=True, db_column='PASSPORT_NO', null=True)),
                ('linkedin_id', models.CharField(db_column='LINKEDIN_ID', max_length=20, primary_key=True, serialize=False)),
                ('github_id', models.CharField(blank=True, db_column='GITHUB_ID', max_length=20, null=True)),
                ('awards', models.CharField(blank=True, db_column='AWARDS', max_length=20, null=True)),
                ('certificates', models.CharField(blank=True, db_column='CERTIFICATES', max_length=20, null=True)),
            ],
            options={
                'db_table': 'imp_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(db_column='USN', max_length=10, primary_key=True, serialize=False)),
                ('student_fname', models.CharField(blank=True, db_column='STUDENT_FNAME', max_length=100, null=True)),
                ('student_lname', models.CharField(blank=True, db_column='STUDENT_LNAME', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=7, null=True)),
                ('email_id', models.CharField(blank=True, db_column='EMAIL_ID', max_length=64, null=True)),
                ('blood_group', models.CharField(blank=True, db_column='BLOOD_GROUP', max_length=4, null=True)),
                ('dept_name', models.CharField(blank=True, db_column='DEPT_NAME', max_length=10, null=True)),
                ('cur_sem', models.IntegerField(blank=True, db_column='CUR_SEM', null=True)),
                ('current_address', models.CharField(blank=True, db_column='CURRENT_ADDRESS', max_length=300, null=True)),
                ('permanent_address', models.CharField(blank=True, db_column='PERMANENT_ADDRESS', max_length=300, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('hostel_or_dayscholar', models.CharField(blank=True, db_column='HOSTEL_OR_DAYSCHOLAR', max_length=20, null=True)),
                ('doc_return_status', models.IntegerField(blank=True, db_column='DOC_RETURN_STATUS', null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacherslist',
            fields=[
                ('tid', models.CharField(db_column='TID', max_length=10, primary_key=True, serialize=False)),
                ('tname', models.CharField(blank=True, db_column='TNAME', max_length=50, null=True)),
            ],
            options={
                'db_table': 'teacherslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('usn', models.OneToOneField(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('classes_attended', models.IntegerField(blank=True, db_column='CLASSES_ATTENDED', null=True)),
                ('total_classes', models.IntegerField(blank=True, db_column='TOTAL_CLASSES', null=True)),
                ('percentage', models.DecimalField(blank=True, db_column='PERCENTAGE', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Backlogs',
            fields=[
                ('usn', models.OneToOneField(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('backlogs_sub_code', models.CharField(db_column='BACKLOGS_SUB_CODE', max_length=100)),
            ],
            options={
                'db_table': 'backlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('usn', models.OneToOneField(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('college_fee', models.IntegerField(db_column='COLLEGE_FEE')),
                ('hostel_fee', models.IntegerField(blank=True, db_column='HOSTEL_FEE', null=True)),
                ('library_fines', models.IntegerField(blank=True, db_column='LIBRARY_FINES', null=True)),
                ('other_fines', models.IntegerField(blank=True, db_column='OTHER_FINES', null=True)),
            ],
            options={
                'db_table': 'fees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('usn', models.OneToOneField(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('girls_or_boys_hostel', models.CharField(blank=True, db_column='GIRLS_OR_BOYS_HOSTEL', max_length=5, null=True)),
                ('room_no', models.CharField(db_column='ROOM_NO', max_length=5)),
                ('block_name', models.CharField(blank=True, db_column='BLOCK_NAME', max_length=10, null=True)),
            ],
            options={
                'db_table': 'hostel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('usn', models.OneToOneField(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('semester', models.IntegerField(blank=True, db_column='SEMESTER', null=True)),
                ('ia1_scores', models.IntegerField(blank=True, db_column='IA1_SCORES', null=True)),
                ('ia2_scores', models.IntegerField(blank=True, db_column='IA2_SCORES', null=True)),
                ('ia3_scores', models.IntegerField(blank=True, db_column='IA3_SCORES', null=True)),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('usn', models.OneToOneField(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('parent_or_gaurdian', models.CharField(blank=True, db_column='PARENT_OR_GAURDIAN', max_length=15, null=True)),
                ('fname', models.CharField(db_column='FNAME', max_length=50)),
                ('father_occupation', models.CharField(blank=True, db_column='FATHER_OCCUPATION', max_length=50, null=True)),
                ('fphone_no', models.IntegerField(blank=True, db_column='FPHONE_NO', null=True)),
                ('femail_id', models.CharField(blank=True, db_column='FEMAIL_ID', max_length=100, null=True)),
                ('mname', models.CharField(blank=True, db_column='MNAME', max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, db_column='MOTHER_OCCUPATION', max_length=50, null=True)),
                ('mphone_no', models.IntegerField(blank=True, db_column='MPHONE_NO', null=True)),
                ('memail_id', models.CharField(blank=True, db_column='MEMAIL_ID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'parent',
                'managed': False,
            },
        ),
    ]
