# Generated by Django 4.1.2 on 2023-02-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='usn',
        ),
        migrations.RemoveField(
            model_name='backlogs',
            name='usn',
        ),
        migrations.DeleteModel(
            name='Departmentcourseinfo',
        ),
        migrations.DeleteModel(
            name='Departmentlist',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='usn',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='usn',
        ),
        migrations.DeleteModel(
            name='ImpInfo',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='usn',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='usn',
        ),
        migrations.DeleteModel(
            name='Teacherslist',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Backlogs',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
