# Generated by Django 4.1.2 on 2022-12-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('stdid', models.OneToOneField(db_column='STDID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataentry.student')),
                ('pname', models.CharField(db_column='PNAME', max_length=100)),
                ('parent_or_gaurdian', models.CharField(blank=True, db_column='PARENT_OR_GAURDIAN', max_length=15, null=True)),
                ('phone_no', models.IntegerField(blank=True, db_column='PHONE_NO', null=True)),
                ('alt_ph_no', models.IntegerField(blank=True, db_column='ALT_PH_NO', null=True)),
                ('occupation', models.CharField(blank=True, db_column='OCCUPATION', max_length=50, null=True)),
                ('email_id', models.CharField(blank=True, db_column='EMAIL_ID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'parent',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
