# Generated by Django 4.1.2 on 2022-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.BigIntegerField(db_column='AADHAR_NO')),
            ],
            options={
                'db_table': 'aadhar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_attended', models.IntegerField(blank=True, db_column='Classes_attended', null=True)),
                ('total_classes', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, db_column='Percentage', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(blank=True, db_column='DEPT_NAME', max_length=20, null=True)),
                ('subcode', models.CharField(db_column='SUBCODE', max_length=10, primary_key=True, serialize=False)),
                ('subjectname', models.TextField(blank=True, db_column='SUBJECTNAME', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='DURATION', null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_fees', models.IntegerField(blank=True, db_column='College_fees', null=True)),
                ('hostel_fees', models.IntegerField(blank=True, db_column='Hostel_fees', null=True)),
                ('library_fines', models.IntegerField(blank=True, db_column='Library_fines', null=True)),
                ('other_fines', models.IntegerField(blank=True, db_column='Other_fines', null=True)),
            ],
            options={
                'db_table': 'fees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls_boys_hostel', models.CharField(blank=True, db_column='Girls_boys_Hostel', max_length=5, null=True)),
                ('room_no', models.CharField(blank=True, db_column='ROOM_NO', max_length=5, null=True)),
                ('block_name', models.CharField(blank=True, db_column='Block_name', max_length=10, null=True)),
            ],
            options={
                'db_table': 'hostel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_10th_percentage', models.BigIntegerField(blank=True, db_column='10TH_PERCENTAGE', null=True)),
                ('number_12th_percentage', models.BigIntegerField(blank=True, db_column='12TH_PERCENTAGE', null=True)),
                ('name_of_school_10th', models.CharField(blank=True, db_column='NAME_OF_SCHOOL_10TH', max_length=20, null=True)),
                ('name_of_college_12th', models.CharField(blank=True, db_column='NAME_OF_COLLEGE_12TH', max_length=20, null=True)),
                ('board_of_education_10th', models.CharField(blank=True, db_column='BOARD_OF_EDUCATION_10TH', max_length=10, null=True)),
                ('board_of_education_12th', models.CharField(blank=True, db_column='BOARD_OF_EDUCATION_12TH', max_length=10, null=True)),
                ('year_of_passing_10th', models.IntegerField(blank=True, db_column='YEAR_OF_PASSING_10TH', null=True)),
                ('year_of_passing_12th', models.IntegerField(blank=True, db_column='YEAR_OF_PASSING_12TH', null=True)),
                ('education_gap', models.IntegerField(blank=True, db_column='EDUCATION_GAP', null=True)),
                ('admission_quota_name', models.CharField(blank=True, db_column='ADMISSION_QUOTA_NAME', max_length=10, null=True)),
                ('rank_from_entrance', models.BigIntegerField(blank=True, db_column='RANK_FROM_ENTRANCE', null=True)),
                ('bank_name', models.CharField(blank=True, db_column='BANK_NAME', max_length=20, null=True)),
                ('bank_account_no', models.BigIntegerField(blank=True, db_column='BANK_ACCOUNT_NO', null=True)),
                ('pan_no', models.BigIntegerField(blank=True, db_column='PAN_NO', null=True)),
                ('voter_id_no', models.BigIntegerField(blank=True, db_column='VOTER_ID_NO', null=True)),
                ('passport_no', models.BigIntegerField(blank=True, db_column='PASSPORT_NO', null=True)),
                ('linkden_id', models.CharField(blank=True, db_column='LINKDEN_ID', max_length=20, null=True)),
                ('github_id', models.CharField(blank=True, db_column='GITHUB_ID', max_length=20, null=True)),
                ('awards', models.CharField(blank=True, db_column='AWARDS', max_length=20, null=True)),
                ('certificates', models.CharField(blank=True, db_column='CERTIFICATES', max_length=20, null=True)),
            ],
            options={
                'db_table': 'imp_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(db_column='SEMESTER')),
                ('semester_sub_scores', models.BigIntegerField(blank=True, db_column='SEMESTER_SUB_SCORES', null=True)),
                ('no_of_backlogs', models.IntegerField(blank=True, db_column='NO_OF_BACKLOGS', null=True)),
                ('back_log_sub_code', models.CharField(blank=True, db_column='BACK_LOG_SUB_CODE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(db_column='SID', max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, db_column='Student_name', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=7, null=True)),
                ('email_id', models.CharField(blank=True, db_column='Email_id', max_length=64, null=True)),
                ('current_address', models.CharField(blank=True, db_column='Current_Address', max_length=300, null=True)),
                ('permanent_address', models.CharField(blank=True, db_column='Permanent_Address', max_length=300, null=True)),
                ('cur_sem', models.IntegerField(blank=True, db_column='Cur_Sem', null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('hostelorday_scholar', models.CharField(blank=True, db_column='HostelORDay_Scholar', max_length=20, null=True)),
                ('doc_return_status', models.IntegerField(blank=True, db_column='DOC_return_status', null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, db_column='TID', max_length=10, null=True)),
                ('tname', models.CharField(blank=True, db_column='TNAME', max_length=50, null=True)),
                ('subname', models.CharField(blank=True, db_column='SUBNAME', max_length=20, null=True)),
                ('personal_info', models.CharField(blank=True, db_column='PERSONAL_INFO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
